pipeline:
  build:
    image: node:10
    commands:
      - npm ci
      - npm run ci
      - npm run test
  slack:
    image: plugins/slack
    username: Cyclops
    webhook: https://hooks.slack.com/services/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
    channel: ci
    icon_url: https://picsum.photos/256/256/?random
    template: >
      {{repo.name}} via {{build.author}}
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
